import React, { useState } from 'react';
import { Scanner } from '@yudiel/react-qr-scanner';
import axios from 'axios';
import { QrCode, CheckCircle, AlertCircle, ArrowLeft, ShieldCheck, Keypad } from 'lucide-react';

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:5001';

export default function App() {
  // Application Steps: 'SCAN', 'PIN', 'SUCCESS', 'FAILED'
  const [step, setStep] = useState('SCAN');
  
  // Decoded payload state
  const [qrData, setQrData] = useState(null);
  const [scanError, setScanError] = useState('');
  
  // PIN state
  const [pin, setPin] = useState('');
  const [pinError, setPinError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  // Transaction result
  const [txnResult, setTxnResult] = useState(null);

  // Manual QR input string (for easy desktop testing)
  const [manualInput, setManualInput] = useState('');
  const [showManualInput, setShowManualInput] = useState(false);

  // Parse QR string payload
  const parseQRData = (rawText) => {
    try {
      setScanError('');
      if (!rawText) return;
      const parsed = typeof rawText === 'string' ? JSON.parse(rawText) : rawText;

      if (!parsed.transactionId || !parsed.orderId) {
        throw new Error('Invalid QR Code: Missing orderId or transactionId');
      }

      setQrData(parsed);
      setStep('PIN');
      setPin('');
      setPinError('');
    } catch (err) {
      console.error('Scan parse error:', err);
      setScanError(err.message || 'Invalid QR Code payload format');
    }
  };

  // Handle QR scanner result callback
  const handleScan = (result) => {
    if (result && result.length > 0) {
      const scannedValue = result[0]?.rawValue || result[0];
      if (scannedValue) {
        parseQRData(scannedValue);
      }
    }
  };

  // Handle keypad button clicks
  const handleKeyClick = (val) => {
    if (pinError) setPinError('');
    if (val === 'backspace') {
      setPin((prev) => prev.slice(0, -1));
    } else if (val === 'clear') {
      setPin('');
    } else if (pin.length < 4) {
      setPin((prev) => prev + val);
    }
  };

  // Process payment upon correct PIN
  const handlePaymentSubmit = async (statusOverride) => {
    const finalStatus = statusOverride || 'success';

    if (finalStatus === 'success' && pin !== '1234') {
      setPinError('Incorrect UPI PIN. Use dummy PIN: 1234');
      return;
    }

    setIsSubmitting(true);
    setPinError('');

    try {
      const response = await axios.post(`${BACKEND_URL}/api/payment/process`, {
        transactionId: qrData.transactionId,
        orderId: qrData.orderId,
        amount: qrData.amount,
        status: finalStatus,
      });

      setTxnResult(response.data);
      if (finalStatus === 'success') {
        setStep('SUCCESS');
      } else {
        setStep('FAILED');
      }
    } catch (err) {
      console.error('Payment processing error:', err);
      setPinError(err.response?.data?.message || 'Failed to communicate with payment backend server');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Reset to initial scan state
  const resetFlow = () => {
    setStep('SCAN');
    setQrData(null);
    setPin('');
    setPinError('');
    setScanError('');
    setTxnResult(null);
    setManualInput('');
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col items-center justify-center p-4">
      {/* Mobile-styled Container */}
      <div className="w-full max-w-md bg-slate-900 border border-slate-800 rounded-3xl shadow-2xl overflow-hidden flex flex-col min-h-[640px] relative">
        
        {/* Header */}
        <header className="bg-slate-900 border-b border-slate-800 p-4 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <ShieldCheck className="w-6 h-6 text-emerald-400" />
            <span className="font-bold text-lg text-slate-100 tracking-wide">PayFast UPI</span>
          </div>
          {step !== 'SCAN' && (
            <button
              onClick={resetFlow}
              className="text-xs bg-slate-800 hover:bg-slate-700 px-3 py-1.5 rounded-full flex items-center gap-1 text-slate-300 transition"
            >
              <ArrowLeft className="w-3.5 h-3.5" /> Scan QR
            </button>
          )}
        </header>

        {/* STEP 1: SCANNER VIEW */}
        {step === 'SCAN' && (
          <div className="flex-1 flex flex-col items-center justify-between p-6 text-center">
            <div>
              <h2 className="text-xl font-bold text-slate-100 mb-1">Scan Payment QR</h2>
              <p className="text-sm text-slate-400">Point scanner at QR code generated by Delivery App</p>
            </div>

            {/* Scanner Area */}
            <div className="w-full max-w-[280px] h-[280px] my-4 rounded-2xl overflow-hidden border-2 border-emerald-500/50 shadow-lg relative bg-black flex items-center justify-center">
              <Scanner
                onScan={handleScan}
                onError={(error) => console.log('Scanner error:', error)}
                styles={{ container: { width: '100%', height: '100%' } }}
              />
            </div>

            {scanError && (
              <div className="w-full bg-red-950/80 border border-red-800 text-red-300 text-xs p-3 rounded-xl flex items-center gap-2 mb-2">
                <AlertCircle className="w-4 h-4 flex-shrink-0" />
                <span>{scanError}</span>
              </div>
            )}

            {/* Manual QR Input Fallback for testing without camera */}
            <div className="w-full mt-2">
              <button
                onClick={() => setShowManualInput(!showManualInput)}
                className="text-xs text-emerald-400 hover:underline mb-2 block w-full text-center"
              >
                {showManualInput ? 'Hide Manual Paste' : 'Testing without camera? Paste QR String'}
              </button>

              {showManualInput && (
                <div className="space-y-2">
                  <textarea
                    rows={3}
                    placeholder='Paste {"orderId":"...","transactionId":"...","amount":100}'
                    value={manualInput}
                    onChange={(e) => setManualInput(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-700 rounded-xl p-2 text-xs font-mono text-slate-200 focus:outline-none focus:border-emerald-500"
                  />
                  <button
                    onClick={() => parseQRData(manualInput)}
                    className="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-medium text-xs py-2 rounded-xl transition"
                  >
                    Parse QR Payload
                  </button>
                </div>
              )}
            </div>
          </div>
        )}

        {/* STEP 2: UPI PIN KEYPAD VIEW */}
        {step === 'PIN' && qrData && (
          <div className="flex-1 flex flex-col justify-between p-6">
            {/* Payment Summary */}
            <div className="bg-slate-950 border border-slate-800 p-4 rounded-2xl text-center space-y-1">
              <span className="text-xs font-semibold text-emerald-400 uppercase tracking-wider">Order Payment</span>
              <h3 className="text-3xl font-extrabold text-white">
                ₹ {Number(qrData.amount).toFixed(2)}
              </h3>
              <div className="text-xs text-slate-400 flex justify-center space-x-3 pt-1">
                <span>Order ID: <strong className="text-slate-200">{qrData.orderId}</strong></span>
              </div>
            </div>

            {/* Enter PIN Prompt */}
            <div className="text-center my-4">
              <p className="text-sm text-slate-300 font-medium">Enter 4-Digit UPI PIN</p>
              <p className="text-xs text-slate-500 mt-0.5">(Dummy PIN: <span className="font-mono text-emerald-400 font-bold">1234</span>)</p>

              {/* PIN Dots */}
              <div className="flex justify-center space-x-4 my-4">
                {[0, 1, 2, 3].map((idx) => (
                  <div
                    key={idx}
                    className={`w-4 h-4 rounded-full border-2 transition-all ${
                      pin.length > idx
                        ? 'bg-emerald-400 border-emerald-400 shadow-md shadow-emerald-500/50 scale-110'
                        : 'border-slate-700 bg-slate-950'
                    }`}
                  />
                ))}
              </div>

              {pinError && (
                <p className="text-xs text-red-400 bg-red-950/60 border border-red-800/50 py-1.5 px-3 rounded-lg inline-block">
                  {pinError}
                </p>
              )}
            </div>

            {/* On-screen Keypad */}
            <div className="grid grid-cols-3 gap-3 my-2">
              {['1', '2', '3', '4', '5', '6', '7', '8', '9'].map((num) => (
                <button
                  key={num}
                  onClick={() => handleKeyClick(num)}
                  className="bg-slate-800 hover:bg-slate-700 active:bg-slate-600 text-white font-semibold text-xl py-3 rounded-2xl transition shadow"
                >
                  {num}
                </button>
              ))}
              <button
                onClick={() => handleKeyClick('clear')}
                className="bg-slate-800/60 hover:bg-slate-800 text-slate-400 font-medium text-xs py-3 rounded-2xl transition"
              >
                Clear
              </button>
              <button
                onClick={() => handleKeyClick('0')}
                className="bg-slate-800 hover:bg-slate-700 active:bg-slate-600 text-white font-semibold text-xl py-3 rounded-2xl transition shadow"
              >
                0
              </button>
              <button
                onClick={() => handleKeyClick('backspace')}
                className="bg-slate-800/60 hover:bg-slate-800 text-slate-400 font-medium text-sm py-3 rounded-2xl transition flex items-center justify-center"
              >
                ⌫
              </button>
            </div>

            {/* Actions */}
            <div className="space-y-2 mt-2">
              <button
                disabled={pin.length !== 4 || isSubmitting}
                onClick={() => handlePaymentSubmit('success')}
                className={`w-full py-3.5 rounded-2xl font-bold text-sm tracking-wide transition shadow-lg ${
                  pin.length === 4 && !isSubmitting
                    ? 'bg-emerald-500 hover:bg-emerald-400 text-slate-950 shadow-emerald-500/25 cursor-pointer'
                    : 'bg-slate-800 text-slate-500 cursor-not-allowed'
                }`}
              >
                {isSubmitting ? 'Processing Payment...' : 'Pay ₹' + Number(qrData.amount).toFixed(2)}
              </button>

              <button
                onClick={() => handlePaymentSubmit('failed')}
                className="w-full text-xs text-red-400 hover:underline py-1 text-center"
              >
                Simulate Payment Failure
              </button>
            </div>
          </div>
        )}

        {/* STEP 3: SUCCESS CONFIRMATION VIEW */}
        {step === 'SUCCESS' && (
          <div className="flex-1 flex flex-col items-center justify-center p-6 text-center space-y-6">
            <div className="w-20 h-20 bg-emerald-500/20 border-2 border-emerald-400 rounded-full flex items-center justify-center text-emerald-400 animate-bounce">
              <CheckCircle className="w-12 h-12" />
            </div>

            <div>
              <h2 className="text-2xl font-extrabold text-white">Payment Successful!</h2>
              <p className="text-emerald-400 font-medium text-sm mt-1">Thanks for payment to delivery app</p>
            </div>

            <div className="w-full bg-slate-950 border border-slate-800 p-4 rounded-2xl text-left space-y-2 text-xs">
              <div className="flex justify-between border-b border-slate-800 pb-2">
                <span className="text-slate-400">Amount Paid</span>
                <span className="font-bold text-emerald-400 text-sm">₹ {qrData?.amount}</span>
              </div>
              <div className="flex justify-between border-b border-slate-800 pb-2">
                <span className="text-slate-400">Order ID</span>
                <span className="font-semibold text-slate-200">{qrData?.orderId}</span>
              </div>
              <div className="flex justify-between border-b border-slate-800 pb-2">
                <span className="text-slate-400">Transaction ID</span>
                <span className="font-mono text-slate-300 text-[11px] truncate max-w-[180px]">
                  {qrData?.transactionId}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Status</span>
                <span className="font-bold text-emerald-400 uppercase">SUCCESS</span>
              </div>
            </div>

            <button
              onClick={resetFlow}
              className="w-full bg-slate-800 hover:bg-slate-700 text-white font-semibold py-3 rounded-2xl text-sm transition"
            >
              Done / Scan Another QR
            </button>
          </div>
        )}

        {/* STEP 4: FAILED CONFIRMATION VIEW */}
        {step === 'FAILED' && (
          <div className="flex-1 flex flex-col items-center justify-center p-6 text-center space-y-6">
            <div className="w-20 h-20 bg-red-500/20 border-2 border-red-500 rounded-full flex items-center justify-center text-red-500">
              <AlertCircle className="w-12 h-12" />
            </div>

            <div>
              <h2 className="text-2xl font-extrabold text-white">Payment Failed</h2>
              <p className="text-red-400 text-sm mt-1">Transaction was declined or cancelled</p>
            </div>

            <button
              onClick={resetFlow}
              className="w-full bg-slate-800 hover:bg-slate-700 text-white font-semibold py-3 rounded-2xl text-sm transition"
            >
              Try Again
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
